---
name: "Lab 7 -Nodejs project"

run-name: |
      "lab 7  workflow with devops class triggered by ${{github.actor}}
      with ${{github.event_name}} event
      on branch ${{github.repository}}"

on:
  workflow_dispatch:

jobs:
  first-job:
    if: ${{ github.event_name == 'workflow_dispatch'  }}
    runs-on: ubuntu-latest
    steps:
      - name: Checking out to a repository
        uses: actions/checkout@v4
      - name: Printing the content of the file
        run: cat firstfile.txt
      - name: Installing nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "17"
      - name: Checking the versions of php and nodejs
        run: node --version
      - name: run server.js
        run: node server.js &
      - name: wait
        run: sleep 5
      - name: check if running
        run: curl http://localhost:3000 

...
